### ISSUE TITLE
Tell Nogarremi to write comments for his code

### ISSUE THREAD

**Issue by nogarremi** [lizardman301/Lizard-bot-rsf#101]
**What needs to be adjusted? Please describe.**
Nogarremi should comment his code more

**Describe the solution you'd like**
Immediate reconciliation for all functions Nogarremi has created that are lacking comments

**Additional context**
A solid 1/3 of utilities.py

**Comment by lizardman301** [comment]
![image](https://user-images.githubusercontent.com/40240232/109885176-b66a3980-7c43-11eb-9926-8612eb743350.png)

**Comment by nogarremi** [comment]
I'm working on it! I swear!
![image](https://user-images.githubusercontent.com/56323690/109889236-d09f1a00-7c39-11eb-89ca-3df89485c92d.png)
