### ISSUE TITLE
Make bad commands not increment the stats table

### ISSUE THREAD

**Issue by lizardman301** [lizardman301/Lizard-bot-rsf#54]
**Is your feature request related to a problem? Please describe.**
If a command is used, the stats table will increment regardless of if the command works or not.

**Describe the solution you'd like**
Either the stats increment should be moved to the end of the command, or some sort of error check should decrease the stats table if it detects an invalid command

**Describe alternatives you've considered**
Maybe rework error checking as a whole to be more streamlined?

**Additional context**

**Comment by nogarremi** [comment]
A full error rework might be in effect here. I might make Lizard-BOT have its own Exception classes but I have to see what the alternatives are and what will be a good solution
`-Nog`

**Comment by nogarremi** [comment]
I'm going to move forward with the pyhonic example in [this article](https://wiki.python.org/moin/HandlingExceptions#Isn.27t_it_better_to_prevent_then_to_remediate.3F) as the way we handle raising exceptions for functions in commands.py


"This is how I would write it in Python:

```python
def my_function(args):
   process(args)
   if error_condition():
       raise SomeError("An error occurred")
   elif different_error_conditon():
       raise SomeError("A different error occurred")
   more_processing()
   if another_error_conditon():
       raise SomeError("Another error occurred")
   do_more_work()
   return "Success!"
```" - MatsWichmann, wiki.python.org
`-Nog`

**Comment by nogarremi** [comment]
Waiting to make pull req until documentation is updated
