### ISSUE TITLE
Make !botrole not restricted as a TO command

### ISSUE THREAD

**Issue by lizardman301** [lizardman301/Lizard-bot-rsf#55]
**What needs to be adjusted? Please describe.**
Let any user user, use the !botrole command instead of restricting it to just TOs.

**Describe the solution you'd like**
Move the command to the unrestricted section.

**Additional context**
!botrole does not ping anyroles. Would be helpful to find out what the current botrole is, in case someone messes around with it.

**Comment by nogarremi** [comment]
More complication because of how I was making the return not ping the role. I pull the role name by comparing the user's role ID with the botrole ID. I'll see if I can find a workaround to make it accessible to anybody

```python
    for role in user.roles:
        if role.id == read_db('guild', 'botrole', kwargs['guild']):
            return "The bot role is {0}".format(bold(role.name))```
