### ISSUE TITLE
Update !pingtest

### ISSUE THREAD

**Issue by lizardman301** [lizardman301/Lizard-bot-rsf#62]
**What needs to be adjusted? Please describe.**
currently ping test has an outdated string of text to go along with the ping.

**Describe the solution you'd like**
Replace it with a more generic "Use the this site for ping tests: https://testmyspeed.onl/" or something similar

**Additional context**
Current Text
![image](https://user-images.githubusercontent.com/40240232/106539126-04fcaa80-64c3-11eb-8991-df251c7eeda4.png)

**Comment by lautaropastorino** [comment]
I'll work on this

**Comment by nogarremi** [comment]
I'll merge this in for now since I'm working on database changes to make this an editable command
`-Nog`
