### ISSUE TITLE
Add a checkin option via discord

### ISSUE THREAD

**Issue by lizardman301** [lizardman301/Lizard-bot-rsf#84]
**Is your feature request related to a problem? Please describe.**
Some TOs want the ability for users to do mostly everything via discord rather then rely on a challonge homepage.

**Describe the solution you'd like**
Add a subcommand to challonge `!challonge here` to allow users to checkin. They must have their nick in discord contain their challonge username for the user they want to check in.

**Describe alternatives you've considered**
We can't use `!challonge checkin` as thats already in use. Also this should be done after we let TOs mute specific commands.

**Additional context**
Just an fyi, tekken tournaments use the format where discord users have the nick "<challonge name> <steam friend code>" to make adding and finding players as easy as possible.

**Comment by nogarremi** [comment]
So we are going the route with `!challonge here` and the user MUST have their Challonge display(bracket) name in their Discord nickname?
`-Nog`

**Comment by lizardman301** [comment]
Yes. In order to accommodate tournies who have more than just the challonge nickname in their discord nickname (IE tekken tournies having the steam friend ID in the nick name), the bot should see if a challonge nick exists in part of a discord nick.  If so then check that one in

**Comment by nogarremi** [comment]
Just wanted to make sure we weren't accepting arguments for this.
`-Nog`
