### ISSUE TITLE
Add a way for users to find tournaments via the bot

### ISSUE THREAD

**Issue by lizardman301** [lizardman301/Lizard-bot-rsf#89]
**Is your feature request related to a problem? Please describe.**
It could be useful for users to be able to see events that are happening throughout the fgc within the bot.

**Describe the solution you'd like**
Create a new command such as `!events <day> <game>` which would list events happening on a specific day for whatever game. TOs should be able to add their entries into the list.

**Describe alternatives you've considered**
This could be done either with a built in database, with a google sheets, or maybe even using a twitter feed. Lots of things could be done

**Additional context**
Requested by puppyswarm

**Comment by lizardman301** [comment]
While I think this would be a great idea for the bot, i think the amount of moderation this requires would be something Nog and I would not like to maintain. Currently anyone is able to invite the bot and be a TO.  If we implemented this system, we would either need to moderate each individual entry or whitelist specific TOs. The first option requires a lot of effort on our parts while the second can be biased.  While I would love to see this implemented in the future, it would be too heavy of a time commitment to be worth it I would feel. I'm open to reconsidering in the future if new ideas are made to implement

**Comment by nogarremi** [comment]
To add onto this, it moves the goal of the bot a little too much in my opinion from being a TO aid to being another social media platform to promote on.

This can be further corroboated by the [Discord Developer Polciy](https://discord.com/developers/docs/policy) which states `You may not use the APIs in any way to: ...target users with advertisements or marketing.`

The area is a bit gray with the inclusion of the word `target` but an inter-guild message that is promoting a tournament could be seen as an advertisement when one considers how the Oxford English Dictionary (hosted on [Lexico](https://www.lexico.com/about) and maintained by [Oxford University Press](https://global.oup.com/?cc=us)) defines [an adveristment](https://www.lexico.com/en/definition/advertisement). The Oxford English Dictionary states an advertisement is `[a] notice or announcement in a public medium promoting a product, service, or event or publicizing a job vacancy.` There doesn't have to be any monetary compensation involved to make something an advertisement which makes it rather broad.

My suggested alternative is to pursue developed social media platforms that can be used without putting a community effort at risk.

In accordance with the above from both Lizardman and myself, this feature request is being denied and closed as `wontfix`
`-Nog`
