### ISSUE TITLE
!stageselect has too many arguments when it has none

### ISSUE THREAD

**Issue by lizardman301** [lizardman301/Lizard-bot-rsf#90]
**Describe the bug**
!stageselect is not functioning properly

**To Reproduce**
1. Type `!stageselect`
2. See error message

**Expected behavior**
Should function just like !rs t7stages

**Screenshots**
![image](https://user-images.githubusercontent.com/40240232/108103564-bd902580-704f-11eb-9c80-ab564f3d482f.png)

**Additional context**
{Add any other context about the problem here.}

**Comment by nogarremi** [comment]
I fixed the issue but I have other pending commits that I'm going to continue to work on before opening a Pull Req for all of that
